# Suma de matrices y multiplicación por escalar
Para sumar matrices es importante que sean del mismo tamaño, de lo contrario no podremos realizar la suma.

![Title](../../src/suma_multiplicacionmatrices.png)

## Suma

In [1]:
import numpy as np
A = np.array([
    [2, -5, -1],
    [-1, -7, -3],
    [-1, -7, -3]
])
B = np.array([
    [3, -5, 2],
    [8, 2, -1],
    [5, 7, 9]
])
A + B

array([[  5, -10,   1],
       [  7,  -5,  -4],
       [  4,   0,   6]])

## Multiplicación por un escalar

In [2]:
B = np.array([
    [3, -5, 2],
    [8, 2, -1],
    [5, 7, 9]
])
B * 3

array([[  9, -15,   6],
       [ 24,   6,  -3],
       [ 15,  21,  27]])

![Title](../../src/ejercicio_multiplicacion_matrices.png)

In [3]:
A = np.array([
    [1, 2, 0],
    [0, 0, -1],
])
B = np.array([
    [0, 1, 3],
    [1, 0, -1]
])
#2X - 4B = 3A
X = (3/2 * A) + (2 * B)
X

array([[ 1.5,  5. ,  6. ],
       [ 2. ,  0. , -3.5]])