# Introducción a las matrices
Una matriz es una representación de datos.

In [26]:
import numpy as np
A = np.array([
    [2, -5, -1],
    [-1, -7, -3]
])
print('A = {}'.format(A))

A = [[ 2 -5 -1]
 [-1 -7 -3]]
m = 2, n = 3
A = (2, 3)


Donde m = cantidad filas y n = cantidad columnas.

In [29]:
m = len(A[:,0])
n = A.shape[1]
print('m = {}, n = {}'.format(m, n))
print('A = {}'.format(A.shape))

m = 2, n = 3
A = (2, 3)


## Matriz Transpuesta

In [41]:
B = np.array([
    [3,5,1],
    [9,3,5],
    [4,7,8],
    [3,6,2]
])
print('B = {}'.format(B))
print('T = {}'.format(B.T))

B = [[3 5 1]
 [9 3 5]
 [4 7 8]
 [3 6 2]]
T = [[3 9 4 3]
 [5 3 7 6]
 [1 5 8 2]]


## Matriz Identidad

In [45]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

![title](../../src/intro_matrices.png)

![title](../../src/tipo_matrices.png)